schema_version: 1

context:
  name: aioserial
  version: 1.3.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 702bf03b0eb84b8ef2d8dac5cb925e1e685dce98f77b125569bc6fd2b3b58228

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - poetry
  run:
    - pyserial
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - aioserial
      python_version: ${{ python_min }}.*
about:
  license: MPL-2.0
  license_file: LICENSE
  summary: pyserial-asyncio for humans
  homepage: http://github.com/changyuheng/aioserial
  repository: https://github.com/changyuheng/aioserial
  documentation: https://github.com/changyuheng/aioserial

extra:
  recipe-maintainers:
    - beenje
    - Benjamin-Lee
